##############################################
########### TMUX KEYBINDINGS #################
##############################################
# bind + I => Installs plugins
# bind + U => Updates plugins
# bind + alt + u => Uninstalls plugins

# bind + S => switches to the previously used session

### tmux plugin commands
# bind + I => Installs new plugins, refreshed tmux environment
# bind + U => Updates plugins
# bind + alt + u => Updates plugins

### tmux resurrect commands
# bind + Ctrl-s => save
# bind + Ctrl-r => restore

### tmux sessionlist
# bind + g => fuzzy search sessions
# bind + C => Creates a new session prompting for a name
# bind + X => Kills current session without having to detach from it
# bind + @ => Promote current pane into a new session
# bind + Ctrl + @ => Promote current pane into a new session

##############################################
########### TMUX BASIC SETTINGS ##############
##############################################

# basic settings
set -g mouse on
set -g history-limit 1024
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g escape-time 10

# setting the prefix
set -g prefix C-b
bind C-b send-prefix

# copy settings
unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v \
  send-keys -X begin-selection

bind-key -T copy-mode-vi 'C-v' \
  send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y \
  send-keys -X copy-pipe-and-cancel "pbcopy"

bind-key -T copy-mode-vi MouseDragEnd1Pane \
  send-keys -X copy-pipe-and-cancel "pbcopy"

# reload this settings file
bind q source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# rename the current window
bind-key r command-prompt -I "#W" "rename-window '%%'"
bind-key R command-prompt -I "#S" "rename-session '%%'"

# new window with the same path
bind c new-window -c '#{pane_current_path}'

# splitting window
bind '/' split-window -h -c '#{pane_current_path}'
bind '-' split-window -v -c '#{pane_current_path}'

# resizing windows

# automatic restoring of the tmux sessions
set -g @continuum-restore 'on'


########################################################
############ LIST OF TMUX PLUGINS ######################
########################################################
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-sessionist'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
